#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Run from anywhere: everything is relative to the repo root.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/backend/.env"
PY="$ROOT/.venv/Scripts/python"
[[ -x "$PY" ]] || PY="$ROOT/.venv/bin/python"

SITE="https://hiredesk-app.vercel.app"
API="https://hiredesk-api.vercel.app"
VERCEL_TEAM="team_hnP2WSbOl0854JZfG5T1v0Hm"
VERCEL_API_PROJECT="prj_ToI1fqITN7tc5oTB2Oul0WXkEe6a"   # hiredesk-api

# run_py runs a Python snippet from backend/, so it can import the app and read backend/.env.
run_py() { (cd "$ROOT/backend" && "$PY" -c "$1"); }

TOTAL_STAGES=7

banner "HireDesk: Google sign-in + invitation emails"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Google sign-in: allow the live site"
say "Google only shows sign-in on websites listed on your OAuth client."
open_url "https://console.cloud.google.com/apis/credentials"
step "Sign in as the Google account that owns the HireDesk project, and pick that project (top bar)."
step "Under 'OAuth 2.0 Client IDs', click the client whose ID starts with 285740906915-84cqi4oq."
step "Under 'Authorized JavaScript origins', click '+ Add URI' and paste exactly:"
say "      ${BOLD}${SITE}${RESET}"
note "  (no slash at the end, no path; keep http://localhost:3000 for local work)"
step "Nothing is needed under 'Authorized redirect URIs'. Click 'Save' at the bottom."
pause "Press Enter once you've clicked Save."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Google sign-in: who may sign in"
say "While the app is in 'Testing', only listed test users can sign in."
open_url "https://console.cloud.google.com/auth/audience"
note "  (Older console layout: APIs & Services → OAuth consent screen.)"
step "If 'Publishing status' says Testing, either:"
say  "    a) click 'Publish app' → Confirm, so any Google account can sign in, or"
say  "    b) under 'Test users', '+ Add users' with each person's Gmail address."
note "  HireDesk only asks for name and email, so publishing needs no Google review."
pause "Press Enter when done."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Gmail: 2-Step Verification"
say "Gmail only gives app passwords to accounts with 2-Step Verification on."
open_url "https://myaccount.google.com/signinoptions/twosv"
step "Sign in as the Gmail account that will SEND the invitations (e.g. okechukwuorjionuchie@gmail.com)."
step "If it says 'On', you're done. Otherwise click 'Turn on' and follow Google's steps."
pause "Press Enter once 2-Step Verification is on."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Gmail: app password for HireDesk"
open_url "https://myaccount.google.com/apppasswords"
step "App name: type HireDesk, then click 'Create'."
step "Google shows a 16-letter password in a yellow box. Copy it (spaces don't matter)."
note "  You only see it once. If you lose it, delete it there and create a new one."
ask SMTP_USERNAME "Gmail address that sends the emails (e.g. you@gmail.com):"
while true; do
  ask_secret SMTP_PASSWORD "Paste the app password (hidden):"
  SMTP_PASSWORD="${SMTP_PASSWORD// /}"
  say "Checking the password with Gmail..."
  if SMTP_USERNAME="$SMTP_USERNAME" SMTP_PASSWORD="$SMTP_PASSWORD" run_py "
import os, smtplib
with smtplib.SMTP('smtp.gmail.com', 587, timeout=20) as s:
    s.starttls(); s.login(os.environ['SMTP_USERNAME'], os.environ['SMTP_PASSWORD'])
" 2>/dev/null; then
    printf '  %s✓ Gmail accepted the login%s\n' "$GREEN" "$RESET"
    break
  fi
  warn "Gmail rejected that address/password. Check the address and create a fresh app password."
  confirm "Try again?" || { SKIPPED+=("Gmail app password (re-run this wizard)"); finish; exit 1; }
done
write_env SMTP_HOST "smtp.gmail.com"
write_env SMTP_PORT "587"
write_env SMTP_USERNAME "$SMTP_USERNAME"
write_env SMTP_PASSWORD "$SMTP_PASSWORD"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Test: send a real invitation email"
ask TEST_EMAIL_TO "Send a test invitation to which inbox? (ideally not the sender's own):"
if TEST_EMAIL_TO="$TEST_EMAIL_TO" SITE="$SITE" run_py "
import os, sys
from app.core.email import send_email
from app.users.router import invitation_email
subject, text, html = invitation_email('there', 'HireDesk setup', 'your company', 'interviewer', os.environ['SITE'] + '/login')
sys.exit(0 if send_email(to=os.environ['TEST_EMAIL_TO'], subject='[Test] ' + subject, text=text, html=html) else 1)
"; then
  printf '  %s✓ Sent.%s Check %s (and its Spam folder) for the "Join the team" email.\n' "$GREEN" "$RESET" "$TEST_EMAIL_TO"
  note "  If it landed in Spam, mark it 'Not spam' once so future invites reach the inbox."
else
  warn "Sending failed. Re-run the wizard and re-enter the app password in stage 4."
  SKIPPED+=("test email to $TEST_EMAIL_TO failed")
fi
pause "Press Enter once you've seen the email (or to continue anyway)."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Live site: save the Gmail settings on Vercel"
say "This stores the four SMTP settings on the Vercel project hiredesk-api and redeploys it,"
say "so invitations sent from ${SITE} go out through Gmail."
if confirm "Save to Vercel and redeploy the live backend now?"; then
  if SMTP_USERNAME="$SMTP_USERNAME" SMTP_PASSWORD="$SMTP_PASSWORD" TEAM="$VERCEL_TEAM" P="$VERCEL_API_PROJECT" API="$API" run_py "
import json, os, sys, time, httpx
auth = os.path.join(os.environ['APPDATA'], 'com.vercel.cli', 'Data', 'auth.json')
token = json.load(open(auth))['token']
api = httpx.Client(base_url='https://api.vercel.com', headers={'Authorization': 'Bearer ' + token},
                   params={'teamId': os.environ['TEAM']}, timeout=30)
P = os.environ['P']
values = {'SMTP_HOST': 'smtp.gmail.com', 'SMTP_PORT': '587',
          'SMTP_USERNAME': os.environ['SMTP_USERNAME'], 'SMTP_PASSWORD': os.environ['SMTP_PASSWORD']}
for key, value in values.items():
    r = api.post(f'/v10/projects/{P}/env', params={'teamId': os.environ['TEAM'], 'upsert': 'true'},
                 json={'key': key, 'value': value, 'type': 'sensitive' if key == 'SMTP_PASSWORD' else 'encrypted',
                       'target': ['production', 'preview']})
    print('  saved', key if r.status_code < 300 else key + ' FAILED: ' + r.text[:120])
    if r.status_code >= 300: sys.exit(1)
repo_id = api.get(f'/v9/projects/{P}').json()['link']['repoId']
d = api.post('/v13/deployments', json={'name': 'hiredesk-api', 'project': P, 'target': 'production',
             'gitSource': {'type': 'github', 'repoId': repo_id, 'ref': 'main'}}).json()
print('  redeploying (about a minute)...', flush=True)
for _ in range(90):
    s = api.get('/v13/deployments/' + d['id']).json()
    if s['readyState'] in ('READY', 'ERROR', 'CANCELED'): break
    time.sleep(5)
print('  deployment:', s['readyState'])
ok = s['readyState'] == 'READY' and httpx.get(os.environ['API'] + '/health', timeout=30).status_code == 200
sys.exit(0 if ok else 1)
"; then
    printf '  %s✓ Live backend updated and healthy.%s\n' "$GREEN" "$RESET"
  else
    warn "Saving or redeploying failed. Is the Vercel CLI logged in? (npx vercel login)"
    SKIPPED+=("Vercel: add SMTP_HOST/PORT/USERNAME/PASSWORD to hiredesk-api and redeploy")
  fi
else
  SKIPPED+=("Vercel: add SMTP_HOST/PORT/USERNAME/PASSWORD to hiredesk-api and redeploy")
fi
# Lets the Monday progress-report workflow send through Gmail too (needs the gh CLI).
set_secret SMTP_USERNAME "$SMTP_USERNAME"
set_secret SMTP_PASSWORD "$SMTP_PASSWORD"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Try it on the live site"
open_url "${SITE}/login"
step "Click 'Continue with Google'. If you still see 'Access blocked', wait 5 minutes"
say "    (Google takes a while to apply the new origin) and refresh."
step "Then as admin: Team → Add team member → enter the person's email."
say "    The dialog should say 'We emailed … a link to join'."
pause "Press Enter to finish."

finish
